In [146]:
print("In the name of Allah")

In the name of Allah

In [147]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews

In [148]:
import pandas as pd

In [149]:
df = pd.read_csv("/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv")
df.sample(10)

                                                  review sentiment
36334  Most successful comic book movies usually depe...  positive
18193  The story of Ed Gein is a disturbing and terri...  negative
42619  When I was driving home after work, I bought s...  negative
20568  Paul Thomas Anderson's stylish and compelling ...  positive
25927  Famous and mysterious recluse Raymar, who's so...  positive
43035  I am surprised that there is confusion over th...  positive
14194  another eli roth in the making. self promoting...  negative
8367   I don't know how this movie has received so ma...  negative
5032   The stories were pretty weird, not really funn...  negative
13338  I've enjoyed this movie ever since I was a kid...  positive

In [150]:
df.columns

Index(['review', 'sentiment'], dtype='object')

In [151]:
df['review'][2].lower()

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [152]:
df['review'] = df['review'].str.lower()

In [153]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [154]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

# Remove HTML Tags

In [155]:
import re

def remove_html_tags(text) :
  pattern = re.compile(r"<.*?>")
  return pattern.sub(r"", text)

In [156]:
remove_html_tags(df['review'][3])

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [157]:
df['review'] = df['review'].apply(remove_html_tags)

In [158]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [159]:
text1= '''
Yesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.

For research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.

If you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.

'''

In [160]:
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.\n\nFor research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.\n\nIf you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.\n\n"

# Remove URL

In [161]:
def remove_url(text):
  pattern = re.compile(r"https?://\S+|www\.\S+")
  return pattern.sub(r"",text)

In [162]:
text1 = remove_html_tags(text1)

In [163]:
text1 = remove_url(text1)

In [164]:
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on  and also watched tutorials at \n\nFor research papers, I visited  and read documentation from  One of my friends also shared a blog post available at \n\nIf you'd like to practice coding problems, check out  or  These websites are very helpful for aspiring AI engineers.\n\n"

# Remove Punctuation

In [165]:
import string

## Way 01

In [166]:
exclude = string.punctuation

In [167]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [168]:
def remove_punc(text) :
  for char in exclude :
    text = text.replace(char, "")

  return text

In [169]:
remove_punc("Hello, This is Akib.!")

'Hello This is Akib'

## Way 02

In [170]:
def remove_punc1(text) :
  return text.translate(str.maketrans(' ', ' ', exclude))

In [171]:
remove_punc1("Hello, This is Akib.!")

'Hello This is Akib'

# Chat words treatment

In [172]:
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired",
    "OMG!": "Oh My God",
    "SMH": "Shaking My Head",
    "NGL": "Not Gonna Lie",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "IMO": "In My Opinion",
    "IMHO": "In My Honest Opinion",
    "RN": "Right Now",
    "FR": "For Real",
    "DW": "Don't Worry",
    "ILYSM": "I Love You So Much",
    "OMW": "On My Way",
    "GGWP": "Good Game Well Played",
    "GG": "Good Game",
    "EZ": "Easy",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud"
}

In [173]:
def chat_conversion(text) :
  new_text = []

  for w in text.split() :
    # print(w) AFK
    if w.upper() in chat_words :
      new_text.append(chat_words[w.upper()])
    else :
      new_text.append(w)

  return " ".join(new_text)

In [174]:
chat_conversion("AFK omg! at")

'Away From Keyboard Oh My God at'

# Spell checking

In [175]:
from textblob import TextBlob

In [176]:
incorrect_text = "helloo this is Akib"

In [177]:
textblob = TextBlob(incorrect_text)

In [178]:
textblob.correct().string

'hello this is Skin'

# Stopwords removal

In [179]:
text = """
Yesterday, I was working on a Machine Learning project in PHITRON, and I was trying to understand how the model is performing on the dataset. The dataset is quite large, and it contains a lot of reviews that are written by users from different countries.

I noticed that the model is not performing well for some of the samples, especially those that are very short or have too many stopwords in them. Because of this, I decided to clean the text data and remove unnecessary words that do not contribute much to the meaning of the sentence.

While I was doing this, I also checked how the preprocessing steps like tokenization, lowercasing, and punctuation removal are affecting the dataset. It was interesting to see that after removing stopwords, the text becomes more meaningful and easier for the model to understand.

In addition to that, I was also reading some documentation from https://scikit-learn.org/stable/ and watching tutorials on https://www.youtube.com while comparing different NLP techniques. The goal is to improve the accuracy of the model and make it more robust for real-world applications.

Overall, I think that removing stopwords is an important step in the NLP pipeline because it helps reduce noise and improve performance of machine learning models.
"""

In [180]:
import nltk

In [181]:
from nltk.corpus import stopwords

In [182]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [183]:
# stopwords.words('bengali')

In [184]:
stop_words = set(stopwords.words('english'))

In [185]:
def remove_stopwords( text ) :
  words = text.split()
  # print(words)
  cleaned = []

  for word in words :
    # print(word)
    word = word.lower().strip(string.punctuation)

    # print(word)

    if word and word not in stop_words :
      cleaned.append(word)

  return " ".join(cleaned)

In [186]:
remove_stopwords(text)

'yesterday working machine learning project phitron trying understand model performing dataset dataset quite large contains lot reviews written users different countries noticed model performing well samples especially short many stopwords decided clean text data remove unnecessary words contribute much meaning sentence also checked preprocessing steps like tokenization lowercasing punctuation removal affecting dataset interesting see removing stopwords text becomes meaningful easier model understand addition also reading documentation https://scikit-learn.org/stable watching tutorials https://www.youtube.com comparing different nlp techniques goal improve accuracy model make robust real-world applications overall think removing stopwords important step nlp pipeline helps reduce noise improve performance machine learning models'

In [187]:
df['review'] = df['review'].apply(remove_stopwords)

In [188]:
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy jake think...
4        petter mattei's love time money visually stunn...
                               ...
49995    thought movie right good job creative original...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: object

# Emoji removal

In [189]:
text_with_emoji = '''Yesterday I completed my Machine Learning project on sentiment analysis 😊🔥.
The model performed really well on the IMDB dataset 👍🎯.
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming 📚💡.
However, debugging errors was quite frustrating 😓💻.
Overall, the experience was amazing and I feel more confident now 🚀😄.'''

In [190]:
import re

def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags
        "\U00002700-\U000027BF"  # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [191]:
clean_text = remove_emoji(text_with_emoji)
print(clean_text)

Yesterday I completed my Machine Learning project on sentiment analysis .
The model performed really well on the IMDB dataset .
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming .
However, debugging errors was quite frustrating .
Overall, the experience was amazing and I feel more confident now .

# Tokenization

## NLTK

In [192]:
from nltk.tokenize import word_tokenize,sent_tokenize
import nltk

In [193]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [194]:
sent1 = 'I am going to visit Dhaka!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'Dhaka', '!']

In [195]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [196]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [197]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [198]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

# Spacy

In [199]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [200]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [201]:
for token in doc2:
    print(token)

We
're
here
to
help
!
mail
us
at
nks@gmail.com

In [202]:
doc1

I have a Ph.D in A.I

In [203]:
doc3

A 5km ride cost $10.50

In [204]:
doc4

I am going to visit Dhaka!

# Stemming

In [205]:
from nltk.stem.porter import PorterStemmer

In [206]:
ps = PorterStemmer()

def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [207]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [208]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [209]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

# Lemmatization

In [210]:
import nltk
from nltk.stem import WordNetLemmatizer

In [211]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [212]:
wordnet_lemmatizer = WordNetLemmatizer()

In [213]:
sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."

In [214]:
punctuations="?:!.,;"

In [215]:
sentence_words = nltk.word_tokenize(sentence)

In [216]:
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

In [217]:
sentence_words

['He',
 'was',
 'running',
 'and',
 'eating',
 'at',
 'same',
 'time',
 'He',
 'has',
 'bad',
 'habit',
 'of',
 'swimming',
 'after',
 'playing',
 'long',
 'hours',
 'in',
 'the',
 'Sun']

In [218]:
print("{0:20}{1:20}".format("Word","Lemma"))

Word                Lemma

In [219]:
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun